name: two
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.3.0
  flutter_svg: ^2.0.17
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flip_card: ^0.7.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  permission_handler: ^12.0.0+1
  confetti: ^0.8.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/data/
  uses-material-design: true
