// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmmgsKx5FwmZhrzb2u7O-a5WWfvPbg_oE',
    appId: '1:778724204921:web:98d9d3840f9b37aedb8fa8',
    messagingSenderId: '778724204921',
    projectId: 'twomvp-bfdb7',
    authDomain: 'twomvp-bfdb7.firebaseapp.com',
    storageBucket: 'twomvp-bfdb7.firebasestorage.app',
    measurementId: 'G-GYY802Y9FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgFVWxHobcSNr-HTKkXKBXAUQ5MFL67FQ',
    appId: '1:778724204921:android:4c1ccddd0094c707db8fa8',
    messagingSenderId: '778724204921',
    projectId: 'twomvp-bfdb7',
    storageBucket: 'twomvp-bfdb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWbzHEqWTONP6_g114lJasmGj5Uj8n_8',
    appId: '1:778724204921:ios:86600315e5572355db8fa8',
    messagingSenderId: '778724204921',
    projectId: 'twomvp-bfdb7',
    storageBucket: 'twomvp-bfdb7.firebasestorage.app',
    iosClientId: '778724204921-o200joqrb6bai15ruciccodvvkkegac4.apps.googleusercontent.com',
    iosBundleId: 'com.example.two',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdWbzHEqWTONP6_g114lJasmGj5Uj8n_8',
    appId: '1:778724204921:ios:86600315e5572355db8fa8',
    messagingSenderId: '778724204921',
    projectId: 'twomvp-bfdb7',
    storageBucket: 'twomvp-bfdb7.firebasestorage.app',
    iosClientId: '778724204921-o200joqrb6bai15ruciccodvvkkegac4.apps.googleusercontent.com',
    iosBundleId: 'com.example.two',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmmgsKx5FwmZhrzb2u7O-a5WWfvPbg_oE',
    appId: '1:778724204921:web:2688a426fa723437db8fa8',
    messagingSenderId: '778724204921',
    projectId: 'twomvp-bfdb7',
    authDomain: 'twomvp-bfdb7.firebaseapp.com',
    storageBucket: 'twomvp-bfdb7.firebasestorage.app',
    measurementId: 'G-3TE9FL13D0',
  );
}
